name: eletecapp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  #bloc
  rxdart: ^0.24.1
  equatable: ^1.2.2
  # flutter_bloc: ^6.0.1
  flutter_bloc: ^5.0.1
  flutter_form_bloc: ^0.15.1

  #http
  dio: ^3.0.9
  retrofit: ^1.3.4

  #ui
  animator: ^2.0.1 
  animate_do: ^1.7.2
  animations: ^1.1.1
  photo_view: ^0.9.2
  card_settings: ^1.12.0
  extended_image: ^0.9.0
  pin_code_fields: ^4.0.0
  carousel_slider: ^2.2.1
  pull_to_refresh: ^1.6.0
  progress_dialog: ^1.2.4
  loading_animations: ^2.1.0
  argon_buttons_flutter: ^1.0.5
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  
  #tool
  auto_route: ^0.6.6
  wakelock: ^0.1.4+2
  validators: ^2.0.1
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.3
  url_launcher: ^5.5.0
  flare_flutter: ^2.0.5
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.8
  flutter_form_builder: ^3.11.5
  country_code_picker: ^1.4.0
  form_field_validator: ^1.0.1
  
  #map 
  google_map_location_picker: ^3.3.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter pub run build_runner build
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.7+4
  auto_route_generator: ^0.6.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/title.png
    - assets/images/background.png
    - assets/images/question.png
    - assets/images/user.png
    - assets/images/join.png

    - assets/images/slider-1.jpg
    - assets/images/slider-2.jpg
    - assets/images/slider-3.jpg
    - assets/images/slider-4.jpg
    - assets/images/slider-5.jpg

    - assets/images/ac.png
    - assets/images/eletectrical.png
    - assets/images/plumbing.png
    - assets/images/house.png
    - assets/images/duct.png

    - assets/images/otp.flr
    - assets/images/verify.png


    - assets/google_fonts/